name: CI Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI Workflow
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet_version: 9.0.x

