name: Run every 5 minutes
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo ${{ secrets.SOME_SECRET }}